// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmbmthnanxidjmyjeqid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptYm10aG5hbnhpZGpteWplcWlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTYyMTcsImV4cCI6MjA2NzEzMjIxN30.Eilg-7x-x9ROeXNVbpgLD-dL5XWrX-7KctW5-9EK588";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});